Web/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Core.Entities.References;
using Core.Gateway;
using Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartBreadcrumbs.Attributes;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Web.Config;
using Web.Models;

namespace Web.Controllers
{
	[DefaultBreadcrumb("Home")]
	public class HomeController : Controller
	{
		public List<HomePageInfoViewModel> HomeFeedInfo { get; set; }

		[Authorize]
		public async Task<IActionResult> Index([FromServices]IOptions<AppConfig> options)
		{
			if (System.IO.File.Exists(options.Value.HomeFeedContentPath))
			{
				HomeFeedInfo ??= JsonConvert.DeserializeObject<List<HomePageInfoViewModel>>(await System.IO.File.ReadAllTextAsync(options.Value.HomeFeedContentPath))?.Where(post => !post.Outdated).ToList();
			}
			else
			{
				HomeFeedInfo ??= new List<HomePageInfoViewModel>();
			}
			ViewBag.FeaturedReferences = await GetFeatured();
			ViewBag.LatestReferences = await GetLatest();
			return View(HomeFeedInfo);
		}

		private Task<List<SneakerReference>> GetFeatured()
		{
			var service = HttpContext.RequestServices.GetService<ISneakerReferenceService>();
			return service.GetFeaturedAsync(new[] {"Air Fear Of God 1", "LDWaffle", "Dunk High Premium SB", "Air Jordan 1 Mid SE (GS)", "Yeezy 700 V3", "Air Max 97", "Air Max 720 ISPA", "Joyride Envelope ISPA"},
				new RequestParams {Limit = 15,});
		}

		private Task<List<SneakerReference>> GetLatest()
		{
			var service = HttpContext.RequestServices.GetService<ISneakerReferenceService>();
			return service.GetLatestAsync(15);
		}
	}
}

Web/Controllers/SubscriptionController.cs
using System.Threading.Tasks;
using Core.Services;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
	public class SubscriptionController : Controller
	{
		private IUserService _service;

		public SubscriptionController(IUserService service)
		{
			_service = service;
		}

		[HttpGet]
		[Route("news/subscribe")]
		public async Task<IActionResult> Subscribe(string email)
		{
			try
			{
				await _service.SubscribeAsync(email);
			}
			catch
			{
				return Controllers.FormSubmitResult(Controllers.SubmitResult.Warning,
					"Either you are already subscribed or something went wrong while performing your subscription, if so consider trying again soon");
			}
			return Controllers.FormSubmitResult(Controllers.SubmitResult.Success,
				"Thank you! You are successfully subscribed to the Kicksware newsletter. We won't spam");
		}

		[HttpGet]
		[Route("news/unsubscribe")]
		public IActionResult Unsubscribe(string email)
		{
			_service.UnsubscribeAsync(email);
			return Controllers.FormSubmitResult(Controllers.SubmitResult.Success,
				"Good buy, you are now unsubscribed from Kicksware newsletter");
		}
	}
}

Web/Views/Home/Index.cshtml
@using Core.Entities.References
@using Web.Utils.Bundle
@using Web.Utils.Helpers
@model List<Web.Models.HomePageInfoViewModel>
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
	var featuredReferences = ViewBag.FeaturedReferences as List<SneakerReference>;
	var latestReferences = ViewBag.LatestReferences as List<SneakerReference>;
}

@section Styles
{
	<link rel="stylesheet" href="@Bundle.GetAssetName("home", "css")" asp-append-version="true"/>
	<link href="https://fonts.googleapis.com/css?family=Oxanium:300,400,500,600,700,800,900" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Audiowide:300,400,500,600,700,800,900" rel="stylesheet" type="text/css">
}

<div class="home">
	<section class="main-carousel">
		<!-- Home Slider -->
		<div class="owl-carousel owl-theme home-auto-slider">
			@foreach (var info in Model)
			{
				<!-- Slider Item -->
				<div class="owl-item auto-slider-item">
					<div class="auto-slider-background" style="background-image: url(@info.Image)"></div>
					<div class="auto-slider-content" data-animation-in="fadeIn" data-animation-out="animate-out fadeOut">
						<div class="auto-slider-title">@info.Title</div>
						<div class="auto-slider-subtitle">@info.Description</div>
						<div class="button button_light home_button" id="home-button">
							<a href=@info.ButtonAction>@info.ButtonCaption</a>
						</div>
					</div>
				</div>
			}
		</div>

		<!-- Home Slider Dots -->
		<div class="auto-slider-dots_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="auto-slider-dots">
							<ul class="auto-slider-dots-list">
								@for (var i = 1; i <= Model.Count; i++)
								{
									var classes = new[] {"auto-slider-dot", i == 1 ? "active" : null};
									<li class="@string.Join(' ', classes)">@($"N{i.ToString().PadLeft(2, '0')}")</li>
								}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

	</section>


	@if (featuredReferences != null && featuredReferences.Any())
	{
		<section class="carousel reference-carousel">
			<h3 class="carousel-title">FEATURED MODELS</h3>
			@{
				await Html.RenderPartialAsync("_ReferenceCarouselPartial", featuredReferences);
			}
		</section>
	}

	@if (latestReferences != null && latestReferences.Any())
	{
		<section class="carousel reference-carousel">
			<h3 class="carousel-title">LATEST ARRIVALS</h3>
			@{
				await Html.RenderPartialAsync("_ReferenceCarouselPartial", latestReferences);
			}
		</section>
	}

	<!-- Newsletter -->

	<section class="newsletter">
		<div class="container">
			<div class="row">
				<hr class="newsletter_border"/>
			</div>
			<div class="row">
				<div class="col-lg-8 offset-lg-2">
					<div class="newsletter_content text-center">
						<div class="newsletter_title">Subscribe to our newsletter</div>
						<div class="newsletter_text">
							<p>Subscribe to our newsletter and stay updated on the latest developments and newset features!</p>
						</div>
						<div class="newsletter_form_container">
							<form asp-controller="Subscription" asp-action="Subscribe" id="newsletter_form" class="newsletter_form">
								<input asp-route="email" type="email" class="newsletter_input" required="required">
								<button class="button">
									<span>Subscribe</span>
								</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

@section Scripts
{
	<script src="@Bundle.GetAssetName("home", "js")" asp-append-version="true"></script>
}